trash = list()
trash.append("This page is available on the web!  Help make the Wayback Machine more complete!  Save this url in the Wayback Machine")
trash.append("The Wayback Machine requires your browser to support JavaScript, please email info@archive.org if you have any questions about this.	The Wayback Machine is an initiative of the Internet Archive ,		   a 501(c)(3) non-profit, building a digital library of		   Internet sites and other cultural artifacts in digital form. Other projects include Open Library & archive-it.org .  Your use of the Wayback Machine is subject to the Internet Archive\'s Terms of Use")
trash.append("Hrm.  The Wayback Machine has not archived that URL.")
trash.append("This page is not available on the web  because access is forbidden")
trash.append("This page is provided courtesy of GoDaddy.com, LLC. Copyright  1999-2016 GoDaddy.com, LLC. All rights reserved. Privacy Policy")
trash.append("Search the history of over 362 billion web pages on the Internet.		 search  Search the Wayback Machine			Featured  texts All Texts  latest This Just In  Smithsonian Libraries  FEDLINK (US)  Genealogy  Lincoln Collection  Additional Collections		  Books to Borrow	   Top  American Libraries  Canadian Libraries  Universal Library  Community Texts  Project Gutenberg  Biodiversity Heritage Library  Children's Library		  Open Library	   Books by Language  permanentlegacy  uslprototype		Featured  movies All Video  latest This Just In  Prelinger Archives  Democracy Now!  Occupy Wall Street  TV NSA Clip Library		  TV News	  Top  Animation & Cartoons  Arts & Music  Community Video  Computers & Technology  Cultural & Academic Films  Ephemeral Films  Movies		  Understanding 9/11	  News & Public Affairs  Spirituality & Religion  Sports Videos  Television  Videogame Videos  Vlogs  Youth Media		Featured  audio All Audio  latest This Just In  Grateful Dead  Netlabels  Old Time Radio  78 RPMs and Cylinder Recordings		  Live Music Archive	  Top  Audio Books & Poetry  Community Audio  Computers & Technology  Music, Arts & Culture  News & Public Affairs  Non-English Audio  Radio Programs		  Librivox Free Audiobook	  Spirituality & Religion  Chris & Spigs' Rock & Roll Circus  Podcasts		Featured  software All Software  latest This Just In  Old School Emulation  MS-DOS Games  Historical Software  Classic PC Games  Software Library		  Internet Arcade	  Top  Community Software  MS-DOS  Kodi Archive and Support File  CD-ROM Software  APK  CD-ROM Software Library  Vintage Software		  Console Living Room	  Software Sites  Tucows Software Library  Shareware CD-ROMs  ZX Spectrum  DOOM Level CD  ZX Spectrum Library: Games  CD-ROM Images		Featured  image All Image  latest This Just In  Flickr Commons  Occupy Wall Street Flickr  Cover Art  USGS Maps		  Metropolitan Museum	  Top  NASA Images  Solar System Collection  Ames Research Center		  Brooklyn Museum			  web	texts	movies	audio	software	image   logo	  Toggle navigation		ABOUT  CONTACT  BLOG  PROJECTS  HELP  DONATE  JOBS  VOLUNTEER  PEOPLE		search		 Search metadata	 Search text contents	 Search TV news captions	 Search archived web sites	Advanced Search		 upload UPLOAD	person SIGN IN	 ABOUT  CONTACT  BLOG  PROJECTS  HELP  DONATE  JOBS  VOLUNTEER  PEOPLE		   DONATE	  Internet Archive's Wayback Machine		  Latest  Show All")
trash.append("Click here to search for all archived pages under")
trash.append("This page is provided courtesy of GoDaddy.com, LLC. Copyright  1999-2017 GoDaddy.com, LLC. All rights reserved. Privacy Policy")
trash.append("Sorry, there are no results for your search.Search again")
trash.append("The Wayback Machine requires your browser to support JavaScript, please email info@archive.org if you have any questions about this.	 The Wayback Machine is an initiative of the Internet Archive ,		   a 501(c)(3) non-profit, building a digital library of		   Internet sites and other cultural artifacts in digital form. Other projects include Open Library & archive-it.org .  Your use of the Wayback Machine is subject to the Internet Archive's Terms of Use")
trash.append("This page is not available on the web  because page does not exist")
trash.append("Featured  texts All Texts  latest This Just In  Smithsonian Libraries  FEDLINK (US)  Genealogy  Lincoln Collection  Additional Collections")
trash.append("Featured  movies All Video  latest This Just In  Prelinger Archives  Democracy Now!  Occupy Wall Street  TV NSA Clip Library")
trash.append("The Wayback Machine is an initiative of the Internet Archive , a 501(c)(3) non-profit, building a digital library of Internet sites and other cultural artifacts in digital form. Other projects include Open Library & archive-it.org .  Your use of the Wayback Machine is subject to the Internet Archive's Terms of Use")
trash.append("ABOUT  CONTACT  BLOG  PROJECTS  HELP  DONATE  JOBS  VOLUNTEER  PEOPLE		search		 Search metadata	 Search text contents	 Search TV news captions	 Search archived web sites	Advanced Search		 upload UPLOAD	person SIGN IN	 ABOUT  CONTACT  BLOG  PROJECTS  HELP  DONATE  JOBS  VOLUNTEER  PEOPLE		   DONATE	  Internet Archive's Wayback Machine")
trash.append("Featured  software All Software  latest This Just In  Old School Emulation  MS-DOS Games  Historical Software  Classic PC Games  Software Library		  Internet Arcade	  Top  Community Software  MS-DOS  Kodi Archive and Support File  CD-ROM Software  APK  CD-ROM Software Library  Vintage Software		  Console Living Room	  Software Sites  Tucows Software Library  Shareware CD-ROMs  ZX Spectrum  DOOM Level CD  ZX Spectrum Library: Games  CD-ROM Images ")
trash.append("Featured  audio All Audio  latest This Just In  Grateful Dead  Netlabels  Old Time Radio  78 RPMs and Cylinder Recordings")
trash.append("Featured  image All Image  latest This Just In  Flickr Commons  Occupy Wall Street Flickr  Cover Art  USGS Maps		  Metropolitan Museum	  Top  NASA Images  Solar System Collection  Ames Research Center		  Brooklyn Museum			  web	texts	movies	audio	software	image   logo	  Toggle navigation")
trash.append("Live Music Archive	  Top  Audio Books & Poetry  Community Audio  Computers & Technology  Music, Arts & Culture  News & Public Affairs  Non-English Audio  Radio Programs		  Librivox Free Audiobook	  Spirituality & Religion  Podcasts")
trash.append("Search the history of over 362 billion web pages on the Internet.		 search  Search the Wayback Machine")
trash.append("Top  American Libraries  Canadian Libraries  Universal Library  Community Texts  Project Gutenberg  Biodiversity Heritage Library  Children's Library")
trash.append("Sorry.  This URL has been excluded from the Wayback Machine")
trash.append("Chris & Spigs' Rock & Roll Circus")
trash.append("Search the history of over 351 billion web pages on the Internet.         search  Search the Wayback Machine")
trash.append("Is this your domain? Add hosting, email and more.")
trash.append("Want to buy this domain? Our Domain Buy Service can help you get it.")
trash.append("Visit GoDaddy.com for:  New product releases")

def isTrash(content):
	for t in trash:
		if t in content:
			return True
	return False